kind: pipeline
name: default

steps:
- name: test
  image: python:3
  commands:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python -m pytest

trigger:
  event:
  - push
  - rollback
  - pull_request